apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.elixir-uit.sigma2.no
      secretName: wildcard-tls
  rules:
    - host: api.elixir-uit.sigma2.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metatrack-api
                port:
                  number: 80